### ISSUE TITLE
Need release to add to dbt project

### ISSUE THREAD

**Issue by ryan-tangocard** [jgooly/segment#24]
I want to add the package to our project, but am unable to do so without a release version.

**Comment by ryan-tangocard** [comment]
Added it to my project to start to mess with it and it's throwing the following error -
column "universial_alias" does not exist in segment_mapped_actions

**Comment by jgooly** [comment]
Hi @ryan-tangocard - it looks like "universial_alias" is misspelled... I pushed an update to fix this. I also created a release tag. Thanks for the feedback.
